parser: babel-eslint
plugins:
- react
- react-native
- jest
parserOptions:
  ecmaFeatures:
    jsx: true
    modules: true
extends:
- eslint:recommended
- plugin:react/recommended
- airbnb-base
rules:
  arrow-body-style: 0
  dot-notation: 0
  function-paren-newline: 0
  object-curly-newline: 0
  space-before-function-paren: 0
  one-var: 0
  one-var-declaration-per-line: 0
  no-param-reassign: 2
  react/display-name: 0
  camelcase: 0
  class-methods-use-this: 0
  no-underscore-dangle: 0
  max-len:
  - error
  - 150
  no-return-assign: 0
  no-else-return: 0
  import/prefer-default-export: 0
  no-lonely-if: 0
  no-console: 1
  no-alert: 0
  arrow-parens: 0
  react-native/no-unused-styles: 2
  react-native/split-platform-components: 0
  react/no-deprecated: 0
  padded-blocks: 0
  object-curly-spacing: 0
  keyword-spacing: 0
  react/jsx-filename-extension: 0
  react/prop-types: 0
  no-extra-boolean-cast: 0
env:
  jest/globals: true
  react-native/react-native: true
globals:
  fetch: false
  alert: false
